name: omega
description: OMEGA institution app.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.9
  animated_splash_screen: ^1.2.0
  flutter_launcher_icons: ^0.9.2
  simple_animations:
  intl: ^0.17.0
  provider: ^6.0.2
  firebase_core: ^1.13.1
  adaptive_text_field: ^0.0.1-dev.1
  google_maps_flutter: ^2.1.3
  animated_bottom_navigation_bar: ^0.3.2
  elastic_drawer: ^2.0.2
  auto_animated: ^3.0.1
  flutter_animated_dialog: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/omega_logo.jpg"
  flutter_lints: ^1.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
